[2023-08-31T03:48:11.637+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sale_data.process_raw_data manual__2023-08-31T03:48:08.811646+00:00 [queued]>
[2023-08-31T03:48:11.645+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sale_data.process_raw_data manual__2023-08-31T03:48:08.811646+00:00 [queued]>
[2023-08-31T03:48:11.645+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-31T03:48:11.657+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_raw_data> on 2023-08-31 03:48:08.811646+00:00
[2023-08-31T03:48:11.661+0000] {standard_task_runner.py:57} INFO - Started process 5408 to run task
[2023-08-31T03:48:11.664+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sale_data', 'process_raw_data', 'manual__2023-08-31T03:48:08.811646+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpbjwy45mt']
[2023-08-31T03:48:11.665+0000] {standard_task_runner.py:85} INFO - Job 152: Subtask process_raw_data
[2023-08-31T03:48:11.701+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sale_data.process_raw_data manual__2023-08-31T03:48:08.811646+00:00 [running]> on host 888526fa4a36
[2023-08-31T03:48:11.766+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sale_data' AIRFLOW_CTX_TASK_ID='process_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T03:48:08.811646+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T03:48:08.811646+00:00'
[2023-08-31T03:48:11.965+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/generic.py:5516: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

[2023-08-31T03:48:11.971+0000] {warnings.py:110} WARNING - /opt/***/dags/py_callables.py:40: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_needed['Pipeline_exc_datetime'] = exec_datetime

[2023-08-31T03:48:11.991+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-31T03:48:11.999+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=process_sale_data, task_id=process_raw_data, execution_date=20230831T034808, start_date=20230831T034811, end_date=20230831T034811
[2023-08-31T03:48:12.037+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-31T03:48:12.059+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
