[2023-08-31T02:38:30.776+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sale_data.create_result_table manual__2023-08-31T02:38:27.067221+00:00 [queued]>
[2023-08-31T02:38:30.783+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sale_data.create_result_table manual__2023-08-31T02:38:27.067221+00:00 [queued]>
[2023-08-31T02:38:30.784+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-31T02:38:30.795+0000] {taskinstance.py:1327} INFO - Executing <Task(PostgresOperator): create_result_table> on 2023-08-31 02:38:27.067221+00:00
[2023-08-31T02:38:30.799+0000] {standard_task_runner.py:57} INFO - Started process 2032 to run task
[2023-08-31T02:38:30.802+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sale_data', 'create_result_table', 'manual__2023-08-31T02:38:27.067221+00:00', '--job-id', '132', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmplrlpzlh7']
[2023-08-31T02:38:30.803+0000] {standard_task_runner.py:85} INFO - Job 132: Subtask create_result_table
[2023-08-31T02:38:30.843+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sale_data.create_result_table manual__2023-08-31T02:38:27.067221+00:00 [running]> on host 888526fa4a36
[2023-08-31T02:38:30.912+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sale_data' AIRFLOW_CTX_TASK_ID='create_result_table' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T02:38:27.067221+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T02:38:27.067221+00:00'
[2023-08-31T02:38:30.913+0000] {sql.py:265} INFO - Executing: CREATE TABLE IF NOT EXISTS consumption_alcoholic_20230831(
                category VARCHAR NOT NULL,
                sub_category  VARCHAR NOT NULL,
                aggregation_date  DATE NOT NULL,
                millions_of_dollar INT NOT NULL,
                pipeline_exc_datetime DATETIME NOT NULL
            );
            CREATE TABLE IF NOT EXISTS consumption_cereals_bakery_20230831(
                category VARCHAR NOT NULL,
                sub_category  VARCHAR NOT NULL,
                aggregation_date  DATE NOT NULL,
                millions_of_dollar INT NOT NULL,
                pipeline_exc_datetime DATETIME NOT NULL
            );
            CREATE TABLE IF NOT EXISTS consumption_meats_poultry_20230831(
                category VARCHAR NOT NULL,
                sub_category  VARCHAR NOT NULL,
                aggregation_date  DATE NOT NULL,
                millions_of_dollar INT NOT NULL,
                pipeline_exc_datetime DATETIME NOT NULL
            );
[2023-08-31T02:38:31.050+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-08-31T02:38:31.090+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-08-31T02:38:31.093+0000] {sql.py:375} INFO - Running statement: CREATE TABLE IF NOT EXISTS consumption_alcoholic_20230831(
                category VARCHAR NOT NULL,
                sub_category  VARCHAR NOT NULL,
                aggregation_date  DATE NOT NULL,
                millions_of_dollar INT NOT NULL,
                pipeline_exc_datetime DATETIME NOT NULL
            );
            CREATE TABLE IF NOT EXISTS consumption_cereals_bakery_20230831(
                category VARCHAR NOT NULL,
                sub_category  VARCHAR NOT NULL,
                aggregation_date  DATE NOT NULL,
                millions_of_dollar INT NOT NULL,
                pipeline_exc_datetime DATETIME NOT NULL
            );
            CREATE TABLE IF NOT EXISTS consumption_meats_poultry_20230831(
                category VARCHAR NOT NULL,
                sub_category  VARCHAR NOT NULL,
                aggregation_date  DATE NOT NULL,
                millions_of_dollar INT NOT NULL,
                pipeline_exc_datetime DATETIME NOT NULL
            );, parameters: None
[2023-08-31T02:38:31.094+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    **extra_kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedObject: type "datetime" does not exist
LINE 6:                 pipeline_exc_datetime DATETIME NOT NULL
                                              ^

[2023-08-31T02:38:31.102+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=process_sale_data, task_id=create_result_table, execution_date=20230831T023827, start_date=20230831T023830, end_date=20230831T023831
[2023-08-31T02:38:31.112+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 132 for task create_result_table (type "datetime" does not exist
LINE 6:                 pipeline_exc_datetime DATETIME NOT NULL
                                              ^
; 2032)
[2023-08-31T02:38:31.135+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-31T02:38:31.155+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
