[2023-08-31T02:38:29.613+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sale_data.process_raw_data manual__2023-08-31T02:38:27.067221+00:00 [queued]>
[2023-08-31T02:38:29.621+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sale_data.process_raw_data manual__2023-08-31T02:38:27.067221+00:00 [queued]>
[2023-08-31T02:38:29.621+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-31T02:38:29.634+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_raw_data> on 2023-08-31 02:38:27.067221+00:00
[2023-08-31T02:38:29.638+0000] {standard_task_runner.py:57} INFO - Started process 2029 to run task
[2023-08-31T02:38:29.640+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sale_data', 'process_raw_data', 'manual__2023-08-31T02:38:27.067221+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmp94f8peph']
[2023-08-31T02:38:29.642+0000] {standard_task_runner.py:85} INFO - Job 131: Subtask process_raw_data
[2023-08-31T02:38:29.679+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sale_data.process_raw_data manual__2023-08-31T02:38:27.067221+00:00 [running]> on host 888526fa4a36
[2023-08-31T02:38:29.748+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sale_data' AIRFLOW_CTX_TASK_ID='process_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T02:38:27.067221+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T02:38:27.067221+00:00'
[2023-08-31T02:38:29.966+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/generic.py:5516: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

[2023-08-31T02:38:29.973+0000] {warnings.py:110} WARNING - /opt/***/dags/py_callables.py:40: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_needed['Pipeline_exc_datetime'] = exec_datetime

[2023-08-31T02:38:29.998+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-31T02:38:30.006+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=process_sale_data, task_id=process_raw_data, execution_date=20230831T023827, start_date=20230831T023829, end_date=20230831T023830
[2023-08-31T02:38:30.054+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-31T02:38:30.078+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
