[2023-08-30T07:43:02.397+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sale_data.process_raw_data manual__2023-08-30T07:42:59.590781+00:00 [queued]>
[2023-08-30T07:43:02.410+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sale_data.process_raw_data manual__2023-08-30T07:42:59.590781+00:00 [queued]>
[2023-08-30T07:43:02.411+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-30T07:43:02.426+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_raw_data> on 2023-08-30 07:42:59.590781+00:00
[2023-08-30T07:43:02.432+0000] {standard_task_runner.py:57} INFO - Started process 2651 to run task
[2023-08-30T07:43:02.435+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sale_data', 'process_raw_data', 'manual__2023-08-30T07:42:59.590781+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpvwhfjrm3']
[2023-08-30T07:43:02.438+0000] {standard_task_runner.py:85} INFO - Job 58: Subtask process_raw_data
[2023-08-30T07:43:02.493+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sale_data.process_raw_data manual__2023-08-30T07:42:59.590781+00:00 [running]> on host 888526fa4a36
[2023-08-30T07:43:02.558+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sale_data' AIRFLOW_CTX_TASK_ID='process_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T07:42:59.590781+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-30T07:42:59.590781+00:00'
[2023-08-30T07:43:02.655+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/generic.py:5516: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

[2023-08-30T07:43:02.662+0000] {warnings.py:110} WARNING - /opt/***/dags/py_callables.py:34: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_needed['Pipeline_exc_datetime'] = exec_datetime

[2023-08-30T07:43:02.683+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-30T07:43:02.691+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=process_sale_data, task_id=process_raw_data, execution_date=20230830T074259, start_date=20230830T074302, end_date=20230830T074302
[2023-08-30T07:43:02.729+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-30T07:43:02.751+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
