[2023-08-31T03:55:22.755+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sale_data.process_raw_data manual__2023-08-31T03:55:20.596452+00:00 [queued]>
[2023-08-31T03:55:22.763+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sale_data.process_raw_data manual__2023-08-31T03:55:20.596452+00:00 [queued]>
[2023-08-31T03:55:22.763+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-31T03:55:22.774+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): process_raw_data> on 2023-08-31 03:55:20.596452+00:00
[2023-08-31T03:55:22.778+0000] {standard_task_runner.py:57} INFO - Started process 5822 to run task
[2023-08-31T03:55:22.780+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sale_data', 'process_raw_data', 'manual__2023-08-31T03:55:20.596452+00:00', '--job-id', '175', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpa9ven0tr']
[2023-08-31T03:55:22.782+0000] {standard_task_runner.py:85} INFO - Job 175: Subtask process_raw_data
[2023-08-31T03:55:22.819+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sale_data.process_raw_data manual__2023-08-31T03:55:20.596452+00:00 [running]> on host 888526fa4a36
[2023-08-31T03:55:22.884+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sale_data' AIRFLOW_CTX_TASK_ID='process_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T03:55:20.596452+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T03:55:20.596452+00:00'
[2023-08-31T03:55:23.079+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/generic.py:5516: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

[2023-08-31T03:55:23.085+0000] {warnings.py:110} WARNING - /opt/***/dags/py_callables.py:40: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_needed['Pipeline_exc_datetime'] = exec_datetime

[2023-08-31T03:55:23.107+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-08-31T03:55:23.115+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=process_sale_data, task_id=process_raw_data, execution_date=20230831T035520, start_date=20230831T035522, end_date=20230831T035523
[2023-08-31T03:55:23.153+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-08-31T03:55:23.176+0000] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
