[2023-08-30T07:01:33.339+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sale_data.check_file_exist manual__2023-08-30T07:01:32.083759+00:00 [queued]>
[2023-08-30T07:01:33.346+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sale_data.check_file_exist manual__2023-08-30T07:01:32.083759+00:00 [queued]>
[2023-08-30T07:01:33.347+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-30T07:01:33.360+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): check_file_exist> on 2023-08-30 07:01:32.083759+00:00
[2023-08-30T07:01:33.364+0000] {standard_task_runner.py:57} INFO - Started process 597 to run task
[2023-08-30T07:01:33.366+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sale_data', 'check_file_exist', 'manual__2023-08-30T07:01:32.083759+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpu0awn8br']
[2023-08-30T07:01:33.369+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask check_file_exist
[2023-08-30T07:01:33.416+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sale_data.check_file_exist manual__2023-08-30T07:01:32.083759+00:00 [running]> on host 888526fa4a36
[2023-08-30T07:01:33.486+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sale_data' AIRFLOW_CTX_TASK_ID='check_file_exist' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T07:01:32.083759+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-30T07:01:32.083759+00:00'
[2023-08-30T07:01:33.487+0000] {logging_mixin.py:149} INFO - File not found, try again in 5 minutes
[2023-08-30T07:03:34.378+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-08-30T07:03:34.382+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 597. PIDs of all processes in the group: [597]
[2023-08-30T07:03:34.383+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 597
[2023-08-30T07:03:34.389+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-08-30T07:03:34.441+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=597, status='terminated', exitcode=0, started='07:01:32') (597) terminated with exit code 0
