[2023-08-30T06:17:44.486+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sale_data.check_file_exist scheduled__2023-08-29T06:17:42.775938+00:00 [queued]>
[2023-08-30T06:17:44.494+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sale_data.check_file_exist scheduled__2023-08-29T06:17:42.775938+00:00 [queued]>
[2023-08-30T06:17:44.495+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-30T06:17:44.507+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): check_file_exist> on 2023-08-29 06:17:42.775938+00:00
[2023-08-30T06:17:44.512+0000] {standard_task_runner.py:57} INFO - Started process 115 to run task
[2023-08-30T06:17:44.516+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sale_data', 'check_file_exist', 'scheduled__2023-08-29T06:17:42.775938+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpkh21_ly8']
[2023-08-30T06:17:44.518+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask check_file_exist
[2023-08-30T06:17:44.569+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sale_data.check_file_exist scheduled__2023-08-29T06:17:42.775938+00:00 [running]> on host 888526fa4a36
[2023-08-30T06:17:44.727+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sale_data' AIRFLOW_CTX_TASK_ID='check_file_exist' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T06:17:42.775938+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-29T06:17:42.775938+00:00'
[2023-08-30T06:25:23.666+0000] {local_task_job_runner.py:292} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-08-30T06:25:23.670+0000] {process_utils.py:135} INFO - Sending Signals.SIGTERM to group 115. PIDs of all processes in the group: [115]
[2023-08-30T06:25:23.671+0000] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 115
[2023-08-30T06:25:23.672+0000] {taskinstance.py:1517} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-08-30T06:25:23.724+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=115, status='terminated', exitcode=0, started='06:17:44') (115) terminated with exit code 0
