[2023-08-31T02:49:38.560+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sale_data.validate_result manual__2023-08-31T02:49:37.313409+00:00 [queued]>
[2023-08-31T02:49:38.573+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sale_data.validate_result manual__2023-08-31T02:49:37.313409+00:00 [queued]>
[2023-08-31T02:49:38.574+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-31T02:49:38.589+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): validate_result> on 2023-08-31 02:49:37.313409+00:00
[2023-08-31T02:49:38.593+0000] {standard_task_runner.py:57} INFO - Started process 2585 to run task
[2023-08-31T02:49:38.596+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sale_data', 'validate_result', 'manual__2023-08-31T02:49:37.313409+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpgicjg5uz']
[2023-08-31T02:49:38.598+0000] {standard_task_runner.py:85} INFO - Job 142: Subtask validate_result
[2023-08-31T02:49:38.644+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sale_data.validate_result manual__2023-08-31T02:49:37.313409+00:00 [running]> on host 888526fa4a36
[2023-08-31T02:49:38.721+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sale_data' AIRFLOW_CTX_TASK_ID='validate_result' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T02:49:37.313409+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T02:49:37.313409+00:00'
[2023-08-31T02:49:38.727+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-08-31T02:49:38.730+0000] {sql.py:375} INFO - Running statement: SELECT COUNT(*) FROM consumption_alcoholic_20230831, parameters: None
[2023-08-31T02:49:38.731+0000] {sql.py:384} INFO - Rows affected: 1
[2023-08-31T02:49:38.738+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-08-31T02:49:38.741+0000] {sql.py:375} INFO - Running statement: SELECT COUNT(*) FROM consumption_cereals_bakery_20230831, parameters: None
[2023-08-31T02:49:38.743+0000] {sql.py:384} INFO - Rows affected: 1
[2023-08-31T02:49:38.860+0000] {base.py:73} INFO - Using connection ID 'postgres' for task execution.
[2023-08-31T02:49:38.863+0000] {sql.py:375} INFO - Running statement: SELECT COUNT(*) FROM consumption_meats_poultry_20230831, parameters: None
[2023-08-31T02:49:38.864+0000] {sql.py:384} INFO - Rows affected: 1
[2023-08-31T02:49:38.865+0000] {logging_mixin.py:149} INFO - 2235
[2023-08-31T02:49:38.888+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/py_callables.py", line 77, in validate_result
    if alcoholic_tbl_rows == alcoholic_file_rows & cereal_bakery_tbl_rows == cereal_bakery_file_rows &  meat_poultry_tbl_rows == meat_poultry_rows:
TypeError: unsupported operand type(s) for &: 'int' and 'tuple'
[2023-08-31T02:49:38.899+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=process_sale_data, task_id=validate_result, execution_date=20230831T024937, start_date=20230831T024938, end_date=20230831T024938
[2023-08-31T02:49:38.910+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 142 for task validate_result (unsupported operand type(s) for &: 'int' and 'tuple'; 2585)
[2023-08-31T02:49:38.929+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-31T02:49:38.942+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
