[2023-08-31T03:48:10.023+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sale_data.log_info manual__2023-08-31T03:48:08.811646+00:00 [queued]>
[2023-08-31T03:48:10.039+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sale_data.log_info manual__2023-08-31T03:48:08.811646+00:00 [queued]>
[2023-08-31T03:48:10.039+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-31T03:48:10.058+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): log_info> on 2023-08-31 03:48:08.811646+00:00
[2023-08-31T03:48:10.064+0000] {standard_task_runner.py:57} INFO - Started process 5404 to run task
[2023-08-31T03:48:10.071+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'process_sale_data', 'log_info', 'manual__2023-08-31T03:48:08.811646+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpk0emosmg']
[2023-08-31T03:48:10.074+0000] {standard_task_runner.py:85} INFO - Job 150: Subtask log_info
[2023-08-31T03:48:10.133+0000] {task_command.py:410} INFO - Running <TaskInstance: process_sale_data.log_info manual__2023-08-31T03:48:08.811646+00:00 [running]> on host 888526fa4a36
[2023-08-31T03:48:10.453+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sale_data' AIRFLOW_CTX_TASK_ID='log_info' AIRFLOW_CTX_EXECUTION_DATE='2023-08-31T03:48:08.811646+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-31T03:48:08.811646+00:00'
[2023-08-31T03:48:10.455+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/py_callables.py", line 89, in log_task_info
    total_duration = end_date - exec_date
TypeError: unsupported operand type(s) for -: 'str' and 'str'
[2023-08-31T03:48:10.468+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=process_sale_data, task_id=log_info, execution_date=20230831T034808, start_date=20230831T034810, end_date=20230831T034810
[2023-08-31T03:48:10.480+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 150 for task log_info (unsupported operand type(s) for -: 'str' and 'str'; 5404)
[2023-08-31T03:48:10.525+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-31T03:48:10.540+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
